
// This file has been generated by the GUI designer. Do not modify.
namespace PArticulo
{
	public partial class EditarArticulo
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PArticulo.EditarArticulo
			this.Name = "PArticulo.EditarArticulo";
			this.Title = global::Mono.Unix.Catalog.GetString ("EditarArticulo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
